apiVersion: v1
kind: Secret
metadata:
  name: ryuko-matoi-env
type: Opaque
stringData:
  IMAGE: ${IMAGE}
  APP_NAME: ${APP_NAME}
  APP_ENV: ${APP_ENV}dd
  TZ: ${TZ}
  LOG_LEVEL: ${LOG_LEVEL}
  LOG_DIR: ${LOG_DIR}
  WHATSAPP_SESSION_PATH: ${WHATSAPP_SESSION_PATH}
  WHATSAPP_DEVICE_NAME: ${WHATSAPP_DEVICE_NAME}
  WHATSAPP_DATABASE_DIALECT: ${WHATSAPP_DATABASE_DIALECT}
  WHATSAPP_DATABASE_DSN: ${WHATSAPP_DATABASE_DSN}
  WHATSAPP_EVENT_BUFFER_SIZE: "${WHATSAPP_EVENT_BUFFER_SIZE}"
  BRAT_FONT_PATH: ${BRAT_FONT_PATH}
  OCR_PROVIDER: ${OCR_PROVIDER}
  OCR_LANGUAGE: ${OCR_LANGUAGE}
  OCR_BINARY_PATH: ${OCR_BINARY_PATH}
  AI_PROVIDER: ${AI_PROVIDER}
  AI_API_KEY: ${AI_API_KEY}
  AI_MODEL: ${AI_MODEL}
  REMOVE_BG_API_KEY: ${REMOVE_BG_API_KEY}
  REMOVE_BG_API_URL: ${REMOVE_BG_API_URL}
  ANIME_QUOTE_API_URL: ${ANIME_QUOTE_API_URL}
  JOKES_API_URL: ${JOKES_API_URL}
  DISTRO_INFO_API_URL: ${DISTRO_INFO_API_URL}
  DOA_API_URL: ${DOA_API_URL}
  QURAN_API_URL: ${QURAN_API_URL}
  IMAGE_API_URL: ${IMAGE_API_URL}
  ASMAUL_HUSNA_API_URL: ${ASMAUL_HUSNA_API_URL}
