apiVersion: apps/v1
kind: Deployment 
metadata:
  name: beszel-hub
  labels:
    app: beszel 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beszel 
  template:
    metadata:
      labels:
        app: beszel
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: beszel 

