apiVersion: apps/v1
kind: Deployment
metadata:
  name: goatcounter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goatcounter
  template:
    metadata:
      labels:
        app: goatcounter
    spec:
      initContainers:
        - name: init-goatcounter
          image: ${IMAGE}
          command:
            - sh
            - -c
            - |
              if [ ! -f /data/goatcounter.sqlite3 ]; then
              goatcounter db create site \
                -db sqlite+/data/goatcounter.sqlite3 \
                -vhost ${DOMAIN} \
                -user.email ${EMAIL} \
                -user.password ${PASSWORD}
              fi
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: goatcounter-env
                  key: DOMAIN
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: goatcounter-env
                  key: EMAIL
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goatcounter-env
                  key: PASSWORD
          volumeMounts:
            - name: goatcounter-data
              mountPath: /data
      containers:
        - name: goatcounter
          image: ${IMAGE}
          args:
            - serve
            - -listen
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: goatcounter-data
              mountPath: /data
      volumes:
        - name: goatcounter-data
          persistentVolumeClaim:
            claimName: goatcounter-data
