apiVersion: v1
kind: Service
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  type: ClusterIP
  selector:
    app: argocd
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
