apiVersion: v1
kind: Service
metadata:
  name: omniroute
  labels:
    app: omniroute
spec:
  type: ClusterIP
  selector:
    app: omniroute
  ports:
    - port: 80
      targetPort: 20128
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: omniroute-redis
  labels:
    app: omniroute-redis
spec:
  type: ClusterIP
  selector:
    app: omniroute-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
