// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/infra/whatsapp/config.proto

package whatsapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DatabaseDialect string                 `protobuf:"bytes,1,opt,name=database_dialect,json=databaseDialect,proto3" json:"database_dialect,omitempty"`
	DatabaseDsn     string                 `protobuf:"bytes,2,opt,name=database_dsn,json=databaseDsn,proto3" json:"database_dsn,omitempty"`
	PairingPhone    string                 `protobuf:"bytes,3,opt,name=pairing_phone,json=pairingPhone,proto3" json:"pairing_phone,omitempty"`
	ClientName      string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	EventBufferSize int32                  `protobuf:"varint,5,opt,name=event_buffer_size,json=eventBufferSize,proto3" json:"event_buffer_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_internal_infra_whatsapp_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDatabaseDialect() string {
	if x != nil {
		return x.DatabaseDialect
	}
	return ""
}

func (x *Config) GetDatabaseDsn() string {
	if x != nil {
		return x.DatabaseDsn
	}
	return ""
}

func (x *Config) GetPairingPhone() string {
	if x != nil {
		return x.PairingPhone
	}
	return ""
}

func (x *Config) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Config) GetEventBufferSize() int32 {
	if x != nil {
		return x.EventBufferSize
	}
	return 0
}

var File_internal_infra_whatsapp_config_proto protoreflect.FileDescriptor

const file_internal_infra_whatsapp_config_proto_rawDesc = "" +
	"\n" +
	"$internal/infra/whatsapp/config.proto\x12\bwhatsapp\"\xc8\x01\n" +
	"\x06Config\x12)\n" +
	"\x10database_dialect\x18\x01 \x01(\tR\x0fdatabaseDialect\x12!\n" +
	"\fdatabase_dsn\x18\x02 \x01(\tR\vdatabaseDsn\x12#\n" +
	"\rpairing_phone\x18\x03 \x01(\tR\fpairingPhone\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12*\n" +
	"\x11event_buffer_size\x18\x05 \x01(\x05R\x0feventBufferSizeB\fZ\n" +
	"./whatsappb\x06proto3"

var (
	file_internal_infra_whatsapp_config_proto_rawDescOnce sync.Once
	file_internal_infra_whatsapp_config_proto_rawDescData []byte
)

func file_internal_infra_whatsapp_config_proto_rawDescGZIP() []byte {
	file_internal_infra_whatsapp_config_proto_rawDescOnce.Do(func() {
		file_internal_infra_whatsapp_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_whatsapp_config_proto_rawDesc), len(file_internal_infra_whatsapp_config_proto_rawDesc)))
	})
	return file_internal_infra_whatsapp_config_proto_rawDescData
}

var file_internal_infra_whatsapp_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_infra_whatsapp_config_proto_goTypes = []any{
	(*Config)(nil), // 0: whatsapp.Config
}
var file_internal_infra_whatsapp_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infra_whatsapp_config_proto_init() }
func file_internal_infra_whatsapp_config_proto_init() {
	if File_internal_infra_whatsapp_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_whatsapp_config_proto_rawDesc), len(file_internal_infra_whatsapp_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_infra_whatsapp_config_proto_goTypes,
		DependencyIndexes: file_internal_infra_whatsapp_config_proto_depIdxs,
		MessageInfos:      file_internal_infra_whatsapp_config_proto_msgTypes,
	}.Build()
	File_internal_infra_whatsapp_config_proto = out.File
	file_internal_infra_whatsapp_config_proto_goTypes = nil
	file_internal_infra_whatsapp_config_proto_depIdxs = nil
}
