// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/infra/whatsapp/types.proto

package whatsapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QREvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QREvent) Reset() {
	*x = QREvent{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QREvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QREvent) ProtoMessage() {}

func (x *QREvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QREvent.ProtoReflect.Descriptor instead.
func (*QREvent) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{0}
}

func (x *QREvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *QREvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QREvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IncomingMessageEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId          string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderJid       string                 `protobuf:"bytes,3,opt,name=sender_jid,json=senderJid,proto3" json:"sender_jid,omitempty"`
	FromMe          bool                   `protobuf:"varint,4,opt,name=from_me,json=fromMe,proto3" json:"from_me,omitempty"`
	Body            string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	QuotedMessageId string                 `protobuf:"bytes,6,opt,name=quoted_message_id,json=quotedMessageId,proto3" json:"quoted_message_id,omitempty"`
	MediaType       string                 `protobuf:"bytes,7,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	MediaMime       string                 `protobuf:"bytes,8,opt,name=media_mime,json=mediaMime,proto3" json:"media_mime,omitempty"`
	MediaData       []byte                 `protobuf:"bytes,9,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Raw             []byte                 `protobuf:"bytes,11,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IncomingMessageEvent) Reset() {
	*x = IncomingMessageEvent{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessageEvent) ProtoMessage() {}

func (x *IncomingMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessageEvent.ProtoReflect.Descriptor instead.
func (*IncomingMessageEvent) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{1}
}

func (x *IncomingMessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *IncomingMessageEvent) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *IncomingMessageEvent) GetSenderJid() string {
	if x != nil {
		return x.SenderJid
	}
	return ""
}

func (x *IncomingMessageEvent) GetFromMe() bool {
	if x != nil {
		return x.FromMe
	}
	return false
}

func (x *IncomingMessageEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *IncomingMessageEvent) GetQuotedMessageId() string {
	if x != nil {
		return x.QuotedMessageId
	}
	return ""
}

func (x *IncomingMessageEvent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *IncomingMessageEvent) GetMediaMime() string {
	if x != nil {
		return x.MediaMime
	}
	return ""
}

func (x *IncomingMessageEvent) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *IncomingMessageEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IncomingMessageEvent) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type SendTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{2}
}

func (x *SendTextRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextResponse) Reset() {
	*x = SendTextResponse{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextResponse) ProtoMessage() {}

func (x *SendTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextResponse.ProtoReflect.Descriptor instead.
func (*SendTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{3}
}

func (x *SendTextResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ImageBytes    []byte                 `protobuf:"bytes,2,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImageRequest) Reset() {
	*x = SendImageRequest{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImageRequest) ProtoMessage() {}

func (x *SendImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImageRequest.ProtoReflect.Descriptor instead.
func (*SendImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{4}
}

func (x *SendImageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendImageRequest) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

func (x *SendImageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

type SendImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImageResponse) Reset() {
	*x = SendImageResponse{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImageResponse) ProtoMessage() {}

func (x *SendImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImageResponse.ProtoReflect.Descriptor instead.
func (*SendImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{5}
}

func (x *SendImageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendStickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	StickerWebp   []byte                 `protobuf:"bytes,2,opt,name=sticker_webp,json=stickerWebp,proto3" json:"sticker_webp,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStickerRequest) Reset() {
	*x = SendStickerRequest{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStickerRequest) ProtoMessage() {}

func (x *SendStickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStickerRequest.ProtoReflect.Descriptor instead.
func (*SendStickerRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{6}
}

func (x *SendStickerRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendStickerRequest) GetStickerWebp() []byte {
	if x != nil {
		return x.StickerWebp
	}
	return nil
}

func (x *SendStickerRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SendStickerRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SendStickerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStickerResponse) Reset() {
	*x = SendStickerResponse{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStickerResponse) ProtoMessage() {}

func (x *SendStickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStickerResponse.ProtoReflect.Descriptor instead.
func (*SendStickerResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{7}
}

func (x *SendStickerResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	VideoBytes    []byte                 `protobuf:"bytes,2,opt,name=video_bytes,json=videoBytes,proto3" json:"video_bytes,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Ptt           bool                   `protobuf:"varint,6,opt,name=ptt,proto3" json:"ptt,omitempty"`
	GifPlayback   bool                   `protobuf:"varint,7,opt,name=gif_playback,json=gifPlayback,proto3" json:"gif_playback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVideoRequest) Reset() {
	*x = SendVideoRequest{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVideoRequest) ProtoMessage() {}

func (x *SendVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVideoRequest.ProtoReflect.Descriptor instead.
func (*SendVideoRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{8}
}

func (x *SendVideoRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendVideoRequest) GetVideoBytes() []byte {
	if x != nil {
		return x.VideoBytes
	}
	return nil
}

func (x *SendVideoRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *SendVideoRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *SendVideoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendVideoRequest) GetPtt() bool {
	if x != nil {
		return x.Ptt
	}
	return false
}

func (x *SendVideoRequest) GetGifPlayback() bool {
	if x != nil {
		return x.GifPlayback
	}
	return false
}

type SendVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVideoResponse) Reset() {
	*x = SendVideoResponse{}
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVideoResponse) ProtoMessage() {}

func (x *SendVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_whatsapp_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVideoResponse.ProtoReflect.Descriptor instead.
func (*SendVideoResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_whatsapp_types_proto_rawDescGZIP(), []int{9}
}

func (x *SendVideoResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_internal_infra_whatsapp_types_proto protoreflect.FileDescriptor

const file_internal_infra_whatsapp_types_proto_rawDesc = "" +
	"\n" +
	"#internal/infra/whatsapp/types.proto\x12\bwhatsapp\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\aQREvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xef\x02\n" +
	"\x14IncomingMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"sender_jid\x18\x03 \x01(\tR\tsenderJid\x12\x17\n" +
	"\afrom_me\x18\x04 \x01(\bR\x06fromMe\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12*\n" +
	"\x11quoted_message_id\x18\x06 \x01(\tR\x0fquotedMessageId\x12\x1d\n" +
	"\n" +
	"media_type\x18\a \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"media_mime\x18\b \x01(\tR\tmediaMime\x12\x1d\n" +
	"\n" +
	"media_data\x18\t \x01(\fR\tmediaData\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03raw\x18\v \x01(\fR\x03raw\">\n" +
	"\x0fSendTextRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"1\n" +
	"\x10SendTextResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"f\n" +
	"\x10SendImageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1f\n" +
	"\vimage_bytes\x18\x02 \x01(\fR\n" +
	"imageBytes\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\"2\n" +
	"\x11SendImageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"~\n" +
	"\x12SendStickerRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12!\n" +
	"\fsticker_webp\x18\x02 \x01(\fR\vstickerWebp\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\"4\n" +
	"\x13SendStickerResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xd5\x01\n" +
	"\x10SendVideoRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1f\n" +
	"\vvideo_bytes\x18\x02 \x01(\fR\n" +
	"videoBytes\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x10\n" +
	"\x03ptt\x18\x06 \x01(\bR\x03ptt\x12!\n" +
	"\fgif_playback\x18\a \x01(\bR\vgifPlayback\"2\n" +
	"\x11SendVideoResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageIdB\fZ\n" +
	"./whatsappb\x06proto3"

var (
	file_internal_infra_whatsapp_types_proto_rawDescOnce sync.Once
	file_internal_infra_whatsapp_types_proto_rawDescData []byte
)

func file_internal_infra_whatsapp_types_proto_rawDescGZIP() []byte {
	file_internal_infra_whatsapp_types_proto_rawDescOnce.Do(func() {
		file_internal_infra_whatsapp_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_whatsapp_types_proto_rawDesc), len(file_internal_infra_whatsapp_types_proto_rawDesc)))
	})
	return file_internal_infra_whatsapp_types_proto_rawDescData
}

var file_internal_infra_whatsapp_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_infra_whatsapp_types_proto_goTypes = []any{
	(*QREvent)(nil),               // 0: whatsapp.QREvent
	(*IncomingMessageEvent)(nil),  // 1: whatsapp.IncomingMessageEvent
	(*SendTextRequest)(nil),       // 2: whatsapp.SendTextRequest
	(*SendTextResponse)(nil),      // 3: whatsapp.SendTextResponse
	(*SendImageRequest)(nil),      // 4: whatsapp.SendImageRequest
	(*SendImageResponse)(nil),     // 5: whatsapp.SendImageResponse
	(*SendStickerRequest)(nil),    // 6: whatsapp.SendStickerRequest
	(*SendStickerResponse)(nil),   // 7: whatsapp.SendStickerResponse
	(*SendVideoRequest)(nil),      // 8: whatsapp.SendVideoRequest
	(*SendVideoResponse)(nil),     // 9: whatsapp.SendVideoResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_internal_infra_whatsapp_types_proto_depIdxs = []int32{
	10, // 0: whatsapp.IncomingMessageEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_whatsapp_types_proto_init() }
func file_internal_infra_whatsapp_types_proto_init() {
	if File_internal_infra_whatsapp_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_whatsapp_types_proto_rawDesc), len(file_internal_infra_whatsapp_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_infra_whatsapp_types_proto_goTypes,
		DependencyIndexes: file_internal_infra_whatsapp_types_proto_depIdxs,
		MessageInfos:      file_internal_infra_whatsapp_types_proto_msgTypes,
	}.Build()
	File_internal_infra_whatsapp_types_proto = out.File
	file_internal_infra_whatsapp_types_proto_goTypes = nil
	file_internal_infra_whatsapp_types_proto_depIdxs = nil
}
