apiVersion: v1
kind: Service
metadata:
  name: goatcounter
  labels:
    app: goatcounter
spec:
  type: ClusterIP
  selector:
    app: goatcounter
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
