apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ryuko-matoi-go
  namespace: argocd
spec:
  project: bots
  source:
    repoURL: https://github.com/haikelz/devops.git
    targetRevision: master
    path: k8s/ryuko-matoi-go
  destination:
    server: https://kubernetes.default.svc
    namespace: bots
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
