// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/config/config.proto

package config

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	WhatsApp      *WhatsAppConfig        `protobuf:"bytes,4,opt,name=whats_app,json=whatsApp,proto3" json:"whats_app,omitempty"`
	Ai            *AIConfig              `protobuf:"bytes,5,opt,name=ai,proto3" json:"ai,omitempty"`
	Ocr           *OCRConfig             `protobuf:"bytes,6,opt,name=ocr,proto3" json:"ocr,omitempty"`
	Api           *APIConfig             `protobuf:"bytes,7,opt,name=api,proto3" json:"api,omitempty"`
	Moderation    *ModerationConfig      `protobuf:"bytes,8,opt,name=moderation,proto3" json:"moderation,omitempty"`
	Media         *MediaConfig           `protobuf:"bytes,9,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_internal_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Config) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Config) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Config) GetWhatsApp() *WhatsAppConfig {
	if x != nil {
		return x.WhatsApp
	}
	return nil
}

func (x *Config) GetAi() *AIConfig {
	if x != nil {
		return x.Ai
	}
	return nil
}

func (x *Config) GetOcr() *OCRConfig {
	if x != nil {
		return x.Ocr
	}
	return nil
}

func (x *Config) GetApi() *APIConfig {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *Config) GetModeration() *ModerationConfig {
	if x != nil {
		return x.Moderation
	}
	return nil
}

func (x *Config) GetMedia() *MediaConfig {
	if x != nil {
		return x.Media
	}
	return nil
}

type WhatsAppConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionPath     string                 `protobuf:"bytes,1,opt,name=session_path,json=sessionPath,proto3" json:"session_path,omitempty"`
	DeviceName      string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DatabaseDialect string                 `protobuf:"bytes,3,opt,name=database_dialect,json=databaseDialect,proto3" json:"database_dialect,omitempty"`
	DatabaseDsn     string                 `protobuf:"bytes,4,opt,name=database_dsn,json=databaseDsn,proto3" json:"database_dsn,omitempty"`
	PairingPhone    string                 `protobuf:"bytes,5,opt,name=pairing_phone,json=pairingPhone,proto3" json:"pairing_phone,omitempty"`
	EventBufferSize int32                  `protobuf:"varint,6,opt,name=event_buffer_size,json=eventBufferSize,proto3" json:"event_buffer_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WhatsAppConfig) Reset() {
	*x = WhatsAppConfig{}
	mi := &file_internal_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhatsAppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatsAppConfig) ProtoMessage() {}

func (x *WhatsAppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatsAppConfig.ProtoReflect.Descriptor instead.
func (*WhatsAppConfig) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *WhatsAppConfig) GetSessionPath() string {
	if x != nil {
		return x.SessionPath
	}
	return ""
}

func (x *WhatsAppConfig) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *WhatsAppConfig) GetDatabaseDialect() string {
	if x != nil {
		return x.DatabaseDialect
	}
	return ""
}

func (x *WhatsAppConfig) GetDatabaseDsn() string {
	if x != nil {
		return x.DatabaseDsn
	}
	return ""
}

func (x *WhatsAppConfig) GetPairingPhone() string {
	if x != nil {
		return x.PairingPhone
	}
	return ""
}

func (x *WhatsAppConfig) GetEventBufferSize() int32 {
	if x != nil {
		return x.EventBufferSize
	}
	return 0
}

type AIConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIConfig) Reset() {
	*x = AIConfig{}
	mi := &file_internal_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIConfig) ProtoMessage() {}

func (x *AIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIConfig.ProtoReflect.Descriptor instead.
func (*AIConfig) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *AIConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AIConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type OCRConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Binary        string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRConfig) Reset() {
	*x = OCRConfig{}
	mi := &file_internal_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRConfig) ProtoMessage() {}

func (x *OCRConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRConfig.ProtoReflect.Descriptor instead.
func (*OCRConfig) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *OCRConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OCRConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *OCRConfig) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

type APIConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemoveBgUrl    string                 `protobuf:"bytes,1,opt,name=remove_bg_url,json=removeBgUrl,proto3" json:"remove_bg_url,omitempty"`
	JokesUrl       string                 `protobuf:"bytes,2,opt,name=jokes_url,json=jokesUrl,proto3" json:"jokes_url,omitempty"`
	AnimeQuoteUrl  string                 `protobuf:"bytes,3,opt,name=anime_quote_url,json=animeQuoteUrl,proto3" json:"anime_quote_url,omitempty"`
	DistroInfoUrl  string                 `protobuf:"bytes,4,opt,name=distro_info_url,json=distroInfoUrl,proto3" json:"distro_info_url,omitempty"`
	DoaUrl         string                 `protobuf:"bytes,5,opt,name=doa_url,json=doaUrl,proto3" json:"doa_url,omitempty"`
	QuranUrl       string                 `protobuf:"bytes,6,opt,name=quran_url,json=quranUrl,proto3" json:"quran_url,omitempty"`
	AsmaulHusnaUrl string                 `protobuf:"bytes,7,opt,name=asmaul_husna_url,json=asmaulHusnaUrl,proto3" json:"asmaul_husna_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIConfig) Reset() {
	*x = APIConfig{}
	mi := &file_internal_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIConfig) ProtoMessage() {}

func (x *APIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIConfig.ProtoReflect.Descriptor instead.
func (*APIConfig) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *APIConfig) GetRemoveBgUrl() string {
	if x != nil {
		return x.RemoveBgUrl
	}
	return ""
}

func (x *APIConfig) GetJokesUrl() string {
	if x != nil {
		return x.JokesUrl
	}
	return ""
}

func (x *APIConfig) GetAnimeQuoteUrl() string {
	if x != nil {
		return x.AnimeQuoteUrl
	}
	return ""
}

func (x *APIConfig) GetDistroInfoUrl() string {
	if x != nil {
		return x.DistroInfoUrl
	}
	return ""
}

func (x *APIConfig) GetDoaUrl() string {
	if x != nil {
		return x.DoaUrl
	}
	return ""
}

func (x *APIConfig) GetQuranUrl() string {
	if x != nil {
		return x.QuranUrl
	}
	return ""
}

func (x *APIConfig) GetAsmaulHusnaUrl() string {
	if x != nil {
		return x.AsmaulHusnaUrl
	}
	return ""
}

type ModerationConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlacklistWords []string               `protobuf:"bytes,1,rep,name=blacklist_words,json=blacklistWords,proto3" json:"blacklist_words,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModerationConfig) Reset() {
	*x = ModerationConfig{}
	mi := &file_internal_config_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationConfig) ProtoMessage() {}

func (x *ModerationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationConfig.ProtoReflect.Descriptor instead.
func (*ModerationConfig) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{5}
}

func (x *ModerationConfig) GetBlacklistWords() []string {
	if x != nil {
		return x.BlacklistWords
	}
	return nil
}

type MediaConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemoveBgApiKey string                 `protobuf:"bytes,1,opt,name=remove_bg_api_key,json=removeBgApiKey,proto3" json:"remove_bg_api_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaConfig) Reset() {
	*x = MediaConfig{}
	mi := &file_internal_config_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaConfig) ProtoMessage() {}

func (x *MediaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_config_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaConfig.ProtoReflect.Descriptor instead.
func (*MediaConfig) Descriptor() ([]byte, []int) {
	return file_internal_config_config_proto_rawDescGZIP(), []int{6}
}

func (x *MediaConfig) GetRemoveBgApiKey() string {
	if x != nil {
		return x.RemoveBgApiKey
	}
	return ""
}

var File_internal_config_config_proto protoreflect.FileDescriptor

const file_internal_config_config_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/config/config.proto\x12\x06config\"\xe8\x02\n" +
	"\x06Config\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\x123\n" +
	"\twhats_app\x18\x04 \x01(\v2\x16.config.WhatsAppConfigR\bwhatsApp\x12 \n" +
	"\x02ai\x18\x05 \x01(\v2\x10.config.AIConfigR\x02ai\x12#\n" +
	"\x03ocr\x18\x06 \x01(\v2\x11.config.OCRConfigR\x03ocr\x12#\n" +
	"\x03api\x18\a \x01(\v2\x11.config.APIConfigR\x03api\x128\n" +
	"\n" +
	"moderation\x18\b \x01(\v2\x18.config.ModerationConfigR\n" +
	"moderation\x12)\n" +
	"\x05media\x18\t \x01(\v2\x13.config.MediaConfigR\x05media\"\xf3\x01\n" +
	"\x0eWhatsAppConfig\x12!\n" +
	"\fsession_path\x18\x01 \x01(\tR\vsessionPath\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12)\n" +
	"\x10database_dialect\x18\x03 \x01(\tR\x0fdatabaseDialect\x12!\n" +
	"\fdatabase_dsn\x18\x04 \x01(\tR\vdatabaseDsn\x12#\n" +
	"\rpairing_phone\x18\x05 \x01(\tR\fpairingPhone\x12*\n" +
	"\x11event_buffer_size\x18\x06 \x01(\x05R\x0feventBufferSize\"U\n" +
	"\bAIConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"[\n" +
	"\tOCRConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\"\xfc\x01\n" +
	"\tAPIConfig\x12\"\n" +
	"\rremove_bg_url\x18\x01 \x01(\tR\vremoveBgUrl\x12\x1b\n" +
	"\tjokes_url\x18\x02 \x01(\tR\bjokesUrl\x12&\n" +
	"\x0fanime_quote_url\x18\x03 \x01(\tR\ranimeQuoteUrl\x12&\n" +
	"\x0fdistro_info_url\x18\x04 \x01(\tR\rdistroInfoUrl\x12\x17\n" +
	"\adoa_url\x18\x05 \x01(\tR\x06doaUrl\x12\x1b\n" +
	"\tquran_url\x18\x06 \x01(\tR\bquranUrl\x12(\n" +
	"\x10asmaul_husna_url\x18\a \x01(\tR\x0easmaulHusnaUrl\";\n" +
	"\x10ModerationConfig\x12'\n" +
	"\x0fblacklist_words\x18\x01 \x03(\tR\x0eblacklistWords\"8\n" +
	"\vMediaConfig\x12)\n" +
	"\x11remove_bg_api_key\x18\x01 \x01(\tR\x0eremoveBgApiKeyB\n" +
	"Z\b./configb\x06proto3"

var (
	file_internal_config_config_proto_rawDescOnce sync.Once
	file_internal_config_config_proto_rawDescData []byte
)

func file_internal_config_config_proto_rawDescGZIP() []byte {
	file_internal_config_config_proto_rawDescOnce.Do(func() {
		file_internal_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_config_config_proto_rawDesc), len(file_internal_config_config_proto_rawDesc)))
	})
	return file_internal_config_config_proto_rawDescData
}

var file_internal_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_config_config_proto_goTypes = []any{
	(*Config)(nil),           // 0: config.Config
	(*WhatsAppConfig)(nil),   // 1: config.WhatsAppConfig
	(*AIConfig)(nil),         // 2: config.AIConfig
	(*OCRConfig)(nil),        // 3: config.OCRConfig
	(*APIConfig)(nil),        // 4: config.APIConfig
	(*ModerationConfig)(nil), // 5: config.ModerationConfig
	(*MediaConfig)(nil),      // 6: config.MediaConfig
}
var file_internal_config_config_proto_depIdxs = []int32{
	1, // 0: config.Config.whats_app:type_name -> config.WhatsAppConfig
	2, // 1: config.Config.ai:type_name -> config.AIConfig
	3, // 2: config.Config.ocr:type_name -> config.OCRConfig
	4, // 3: config.Config.api:type_name -> config.APIConfig
	5, // 4: config.Config.moderation:type_name -> config.ModerationConfig
	6, // 5: config.Config.media:type_name -> config.MediaConfig
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_config_config_proto_init() }
func file_internal_config_config_proto_init() {
	if File_internal_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_config_config_proto_rawDesc), len(file_internal_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_config_config_proto_goTypes,
		DependencyIndexes: file_internal_config_config_proto_depIdxs,
		MessageInfos:      file_internal_config_config_proto_msgTypes,
	}.Build()
	File_internal_config_config_proto = out.File
	file_internal_config_config_proto_goTypes = nil
	file_internal_config_config_proto_depIdxs = nil
}
