apiVersion: v1
kind: Secret
metadata:
  name: ai-assistant-env
type: Opaque
stringData:
  SUMOPOD_API_KEY: ${SUMOPOD_API_KEY}
  TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  TELEGRAM_USER_ID: "${TELEGRAM_USER_ID}"
