apiVersion: v1
kind: Secret
metadata:
  name: umami-env
type: Opaque
stringData:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  APP_SECRET: ${APP_SECRET}
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@umami-postgres:5432/${POSTGRES_DB}?sslmode=disable
  DOMAIN: ${DOMAIN}
  EMAIL: ${EMAIL}
  TRACKER_SCRIPT_NAME: ${TRACKER_SCRIPT_NAME}
