apiVersion: v1
kind: Secret
metadata:
  name: ekel-backend-env
type: Opaque
stringData:
  WAKATIME_API_URL: ${WAKATIME_API_URL}
  WAKATIME_API_KEY: ${WAKATIME_API_KEY}
  TURSO_DATABASE_URL: ${TURSO_DATABASE_URL}
  TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  JWT_SECRET: ${JWT_SECRET}
  IHSG_API_URL: ${IHSG_API_URL}
  SECRET_KEY_ADMIN: ${SECRET_KEY_ADMIN}
  SECRET_KEY_CUSTOMER: ${SECRET_KEY_CUSTOMER}
  IMAGE: ${IMAGE}
